In [1]:
#Home work

In [2]:
l = [100, 150, 80, 160, 250]
l1 = []
l2 = []
l3 = []
for i in l:
    if i < 100:
        l1.append(i)
    elif i < 200:
        l2.append(i)
    else:
        l3.append(i)
print(l1)
print(l2)
print(l3)

[80]
[100, 150, 160]
[250]


In [4]:
d = {
    "Ngoc": 1233489688,
    "Chuong": 365689980,
    "Tuan": 3799080909
}
h = [str(k)[-6:] for k in d.values()]
print(h)

['489688', '689980', '080909']


In [9]:
d = {
    'G12': 500,
    'M15': 200,
    'C20': 1000000
}
d2 = {}
for i in d:
    if i.startswith('G'):
        d3 = {'G12': int(500*0.8)}
    elif i.startswith('M'):
        d4 = {'M15': int(200 * 0.7)}
    else:
        d5 = {'C20': int(1000000*0.35)}
d2.update(d3)
d2.update(d4)
d2.update(d5)
print(d2)

{'G12': 400, 'M15': 140, 'C20': 350000}


In [24]:
l = ['Tuan', 'Manh', 'Cuong', 'Lam']
d = {'Tuan': 100, 'Manh':300, 'Hong': 200, 'Manh': 50}
l = []
for i in l:
    t = 0
    for k, v in  d.items():
        if i == k:
            t += d[k]
            l.append(t)
print(l)

[]


# Numpy

In [25]:
import numpy as np

### Numpy: là một thư viện toán học phổ biến và mạnh mẽ của Python. Cho phép làm việc hiểu quả với ma trận và mảng
### Các phần tử của array phải cùng kiểu dtype (ép kiểu xảy ra nếu cần thiết)
### Numpy array là partly mutable: có thể thay đổi các phần tử đang có, nhưng không thể thay đổi kích thước của cả array(no append, remove, delete)

In [26]:
l = [1, 2, 3, 4]
a = np.array(l)
print(a)
print(a.dtype)
print(type(a))

[1 2 3 4]
int64
<class 'numpy.ndarray'>


In [29]:
l = [2, 3, 'htinh']
a = np.array(l) # rule 2 :))) same dtypes
print(a)
print(a.dtype)
print(type(a))


['2' '3' 'htinh']
<U21
<class 'numpy.ndarray'>


In [30]:
a = np.arange(9)
print(a)
print(type(a))
print(a.dtype)

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>
int64


In [31]:
a = np.array([[1, 2], [3, 4]])
print(a)
print(type(a))
print(a.dtype)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
int64


In [32]:
a = np.arange(9)
print(a)
a[0] = 99
print(a)

[0 1 2 3 4 5 6 7 8]
[99  1  2  3  4  5  6  7  8]


In [33]:
a = np.arange(9)
print(a)
del a[0]

[0 1 2 3 4 5 6 7 8]


ValueError: cannot delete array elements

In [34]:
a = np.array([True, False, 1, 2])
print(a)
print(a.dtype)

[1 0 1 2]
int64


In [37]:
a = np.array([1, 2, "A"])
print(a)
print(a.dtype)

['1' '2' 'A']
<U21


In [38]:
a = np.zeros([2, 2])
print(a)

[[0. 0.]
 [0. 0.]]


In [39]:
a = np.ones((1, 2))
a

array([[1., 1.]])

In [40]:
c = np.full((2, 2), 7)
print(c)

[[7 7]
 [7 7]]


In [41]:
d = np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [42]:
e = np.random.random((2, 2))
print(e)

[[0.19795971 0.68115886]
 [0.92816758 0.38200644]]


## Manipulate with Numpy Array

In [44]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

In [45]:
print(a.size)
print(len(a))

3
3


In [46]:
print(b.size)
print(len(b))

4
2


In [47]:
print(a.dtype)
print(b.dtype)

int64
int64


In [48]:
print(a.shape)
print(b.shape) #(rows, columns)

(3,)
(2, 2)


In [49]:
# Dimension
print(a.ndim)
print(b.ndim)

1
2


## Indxing and Slicing

In [55]:
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [59]:
a[0]

np.int64(0)

In [60]:
a[-1]

np.int64(11)

In [61]:
a[:3]

array([0, 1, 2])

In [62]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[:2, 1:3])

[[2 3]
 [6 7]]


## N_D array

In [63]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [64]:
print(a[0, 0])

0


In [65]:
print(a[0])

[0 1 2]


In [66]:
print(a[-1])

[6 7 8]


In [68]:
print(a[:, 0])

[0 3 6]


In [69]:
print(a[:, -1])

[2 5 8]


In [71]:
print(a[:, [0, -1]])

[[0 2]
 [3 5]
 [6 8]]


In [72]:
print(a[:, :])


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Array Math

In [73]:
import numpy as np

In [74]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [78]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [80]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [81]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [82]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [83]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [84]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

In [89]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [90]:
print(v.dot(y))
print(np.dot(x, y))

[115 134]
[[19 22]
 [43 50]]


In [91]:
x = np.array([[1, 2], [3, 4]])
print(np.sum(x))
print(np.sum(x, axis = 0)) #compute sum of each column
print(np.sum(x, axis = 1)) #compute sum of each row

10
[4 6]
[3 7]


In [93]:
x = np.array([[1, 2], [3, 4]])
print(x)
print(x.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


# Vectorization (broadcasting)

In [94]:
import timeit

In [95]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
print(a + 10)
print(timeit.timeit(setup='import numpy as np', stmt='np.arange(10) + 10'))

[10 11 12 13 14 15 16 17 18 19]
2.209292866999931


In [101]:
print([x + 10 for x in a])
print(timeit.timeit(setup='import numpy as np', stmt='np.arange(10) + 10'))

[np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19)]
1.7881839669998953


In [102]:
print(a - 10)

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


In [103]:
print(a * 10)

[ 0 10 20 30 40 50 60 70 80 90]


In [104]:
print(a ** 10)

[         0          1       1024      59049    1048576    9765625
   60466176  282475249 1073741824 3486784401]


# Masking 

In [106]:
a = np.random.randint(-10, 10, size=10)
a

array([  3,   3,   5, -10,   7,   4,   4,  -4,   3,   3])

In [107]:
print(a > 0)

[ True  True  True False  True  True  True False  True  True]


In [108]:
print(a[a > 0])

[3 3 5 7 4 4 3 3]


In [109]:
print(a[a % 2 == 0])

[-10   4   4  -4]


In [110]:
print(a[a >= 0])

[3 3 5 7 4 4 3 3]


In [111]:
print(a[a > 5])

[7]


In [112]:
print(np.all(a > 0))

False


In [113]:
print(np.any(a > 0))

True


# 1 - D array

In [114]:
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [115]:
print(a.min())
print(np.min(a))

0
0


In [117]:
print(a.max())
print(np.max(a))

10
10


In [118]:
print(np.median(a))


5.0


# 2 -D

In [119]:
a = np.arange(100).reshape(10, 10)

In [120]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [121]:
print(a.mean(axis=0)) # mean column-wise

[45. 46. 47. 48. 49. 50. 51. 52. 53. 54.]


In [122]:
print(a.mean(axis=1))
#mean row-wise

[ 4.5 14.5 24.5 34.5 44.5 54.5 64.5 74.5 84.5 94.5]
